# SPDX-FileCopyrightText: 2024 Jomco B.V.
# SPDX-FileCopyrightText: 2024 Topsector Logistiek
# SPDX-FileContributor: Joost Diepenmaat <joost@jomco.nl>
# SPDX-FileContributor: Remco van 't Veer <remco@jomco.nl>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

trusted_list:
  - test-config/ca.cert.pem

parties:
  - party_id: EU.EORI.CLIENT
    party_name: Some Client
    capability_url: ''
    auth_registries:
    - name: BDI Authorization Register
      id: EU.EORI.AUTHORIZATION-REGISTER
      url: http://localhost:9992/
      dataspace_id: ORG.BDI.VGU-DEMO
      dataspace_name: BDI VGU DataSpace
    certificates:
    - test-config/client.cert.pem
    adherence:
      status: Active
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-13T00:00:00.000Z'
    registrar_id: EU.EORI.ASSOCIATION-REGISTER
    roles:
    - role: ServiceConsumer
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-12T00:00:00.000Z'
      loa: 'Low'
      complaiancy_verified: false
      legal_adherence: false
    agreements: []

  - party_id: EU.EORI.AUTHENTICATION-SERVICE
    party_name: Generic Authentication Service
    capability_url: ''
    certificates:
    - test-config/authentication_service.cert.pem
    adherence:
      status: Active
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-13T00:00:00.000Z'
    registrar_id: EU.EORI.ASSOCIATION-REGISTER
    roles:
    - role: ServiceProvider
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-12T00:00:00.000Z'
      loa: 'Low'
      complaiancy_verified: false
      legal_adherence: false
    agreements: []

  - party_id: EU.EORI.ASSOCIATION-REGISTER
    party_name: BDI Association Register
    capability_url: ''
    certificates:
    - test-config/association_register.cert.pem  
    adherence:
      status: Active
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-13T00:00:00.000Z'
    registrar_id: EU.EORI.ASSOCIATION-REGISTER
    roles:
    - role: iShareSatellite
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-12T00:00:00.000Z'
      loa: 'Low'
      complaiancy_verified: false
      legal_adherence: false 
    agreements: []

  - party_id: EU.EORI.AUTHORIZATION-REGISTER
    party_name: BDI Authorization Register
    capability_url: ''
    certificates:
    - test-config/authorization_register.cert.pem
    adherence:
      status: Active
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-13T00:00:00.000Z'
    registrar_id: EU.EORI.ASSOCIATION-REGISTER
    roles:
    - role: iShareSatellite
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-12T00:00:00.000Z'
      loa: 'Low'
      complaiancy_verified: false
      legal_adherence: false 
    agreements: []

  - party_id: EU.EORI.CONNECTOR
    party_name: BDI Connector
    capability_url: ''
    certificates:
    - test-config/connector.cert.pem
    adherence:
      status: Active
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-13T00:00:00.000Z'
    registrar_id: EU.EORI.ASSOCIATION-REGISTER
    roles:
    - role: ServiceProvider
      start_date: '2024-02-12T00:00:00.000Z'
      end_date: '2100-02-12T00:00:00.000Z'
      loa: 'Low'
      complaiancy_verified: false
      legal_adherence: false
    agreements: []
