# SPDX-FileCopyrightText: 2024 Jomco B.V.
# SPDX-FileCopyrightText: 2024 Stichting Connekt
# SPDX-FileContributor: Joost Diepenmaat <joost@jomco.nl>
# SPDX-FileContributor: Remco van 't Veer <remco@jomco.nl>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Check dependency vulnerabilities

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 1' # every monday
      timezone: Europe/Amsterdam
  workflow_call:

jobs:
  "NVD-check":
    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v7

    - uses: jomco/clojure-action@v1
      with: { m2-cache-key: m2-watson }

    - name: Check clojure dependencies
      run: make watson
