# SPDX-FileCopyrightText: 2024 Jomco B.V.
# SPDX-FileCopyrightText: 2024 Stichting Connekt
# SPDX-FileContributor: Joost Diepenmaat <joost@jomco.nl>
# SPDX-FileContributor: Remco van 't Veer <remco@jomco.nl>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Test

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04

    services: # we need postgres for testing the authorization register
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v7

    - uses: jomco/clojure-action@v1
      with: { m2-cache-key: m2-test }

    - name: Install packages
      run: |
        sudo apt-get install -y reuse

    - name: Run make check
      run: |
        make check
      env:
        AR_TEST_DB_NAME: "postgres" # default database in service container
        AR_TEST_DB_USER: "postgres"
        AR_TEST_DB_PASSWORD: "postgres"
